"""search phase1 btree indexes

Global search phase 1 (spec D7): exact match = equality = btree only.
Index audit of every §3.2 phase-1 column:

- permanent_documents.original_filename — no index → ADDED
- tasks.title — no index → ADDED
- notifications.recipient — no index → ADDED
- annual_reports.ita_reference — no index → ADDED
- binders.binder_number — only composite uq_binder_number_per_client
  (client_record_id leading; term-only equality unserved) → ADDED
- advance_payments.period — SKIPPED: partial idx_advance_payment_period_active
  (period WHERE deleted_at IS NULL) serves the search branch, which itself
  filters deleted_at IS NULL
- charges.id — SKIPPED: primary key
- vat_work_items.period — SKIPPED: standalone ix_vat_work_items_period
- annual_reports.tax_year — SKIPPED: idx_annual_report_tax_year_status_active
  (tax_year leading)

No pg_trgm, no GIN — those are the phase-2 entry gate (D7). No enum types.

Revision ID: 8f1039f41468
Revises: 8a1c47d0b3e2
Create Date: 2026-07-21 15:11:17.685434

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f1039f41468"
down_revision: str | Sequence[str] | None = "8a1c47d0b3e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_annual_report_ita_reference", "annual_reports", ["ita_reference"], unique=False
    )
    op.create_index("idx_binder_number", "binders", ["binder_number"], unique=False)
    op.create_index("idx_notification_recipient", "notifications", ["recipient"], unique=False)
    op.create_index(
        "ix_permanent_documents_original_filename",
        "permanent_documents",
        ["original_filename"],
        unique=False,
    )
    op.create_index("idx_tasks_title", "tasks", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_title", table_name="tasks")
    op.drop_index("ix_permanent_documents_original_filename", table_name="permanent_documents")
    op.drop_index("idx_notification_recipient", table_name="notifications")
    op.drop_index("idx_binder_number", table_name="binders")
    op.drop_index("idx_annual_report_ita_reference", table_name="annual_reports")
    # ### end Alembic commands ###
