"""Central registry of application error codes.

Source of truth for every ``DOMAIN.REASON`` code raised from the service layer.
``AppError.code`` is typed to this enum, so the code slot cannot hold a typo, a
free-form string, or a user-facing message. Members subclass ``str`` so the wire
value is unchanged (the enum value is the literal ``DOMAIN.REASON`` string).

See ``docs/backend/error-codes.md`` for the namespace table and the
``DOMAIN.REASON`` format rules.
"""

from enum import Enum


class ErrorCode(str, Enum):
    """Every error code the backend may put in ``error.code``."""

    # ADVANCE_PAYMENT
    ADVANCE_PAYMENT_CLIENT_NOT_FOUND = "ADVANCE_PAYMENT.CLIENT_NOT_FOUND"
    ADVANCE_PAYMENT_CLIENT_RECORD_NOT_FOUND = "ADVANCE_PAYMENT.CLIENT_RECORD_NOT_FOUND"
    ADVANCE_PAYMENT_CONFLICT = "ADVANCE_PAYMENT.CONFLICT"
    ADVANCE_PAYMENT_FREQUENCY_MISMATCH = "ADVANCE_PAYMENT.FREQUENCY_MISMATCH"
    ADVANCE_PAYMENT_FREQUENCY_NOT_SET = "ADVANCE_PAYMENT.FREQUENCY_NOT_SET"
    ADVANCE_PAYMENT_NOT_FOUND = "ADVANCE_PAYMENT.NOT_FOUND"
    ADVANCE_PAYMENT_RATE_INVALID = "ADVANCE_PAYMENT.RATE_INVALID"
    ADVANCE_PAYMENT_VAT_NOT_FILED = "ADVANCE_PAYMENT.VAT_NOT_FILED"
    ADVANCE_PAYMENT_VAT_TURNOVER_NOT_FOUND = "ADVANCE_PAYMENT.VAT_TURNOVER_NOT_FOUND"

    # ANNUAL_REPORT
    ANNUAL_REPORT_ANNEX_VALIDATION_ERROR = "ANNUAL_REPORT.ANNEX_VALIDATION_ERROR"
    ANNUAL_REPORT_AUDIT_ACTOR_REQUIRED = "ANNUAL_REPORT.AUDIT_ACTOR_REQUIRED"
    ANNUAL_REPORT_CLIENT_NOT_FOUND = "ANNUAL_REPORT.CLIENT_NOT_FOUND"
    ANNUAL_REPORT_CONFLICT = "ANNUAL_REPORT.CONFLICT"
    ANNUAL_REPORT_INVALID_STAGE = "ANNUAL_REPORT.INVALID_STAGE"
    ANNUAL_REPORT_INVALID_STATUS = "ANNUAL_REPORT.INVALID_STATUS"
    ANNUAL_REPORT_INVALID_STATUS_FOR_AMEND = "ANNUAL_REPORT.INVALID_STATUS_FOR_AMEND"
    ANNUAL_REPORT_INVALID_STATUS_FOR_AUTOPOPULATE = "ANNUAL_REPORT.INVALID_STATUS_FOR_AUTOPOPULATE"
    ANNUAL_REPORT_INVALID_TYPE = "ANNUAL_REPORT.INVALID_TYPE"
    ANNUAL_REPORT_LINES_ALREADY_EXIST = "ANNUAL_REPORT.LINES_ALREADY_EXIST"
    ANNUAL_REPORT_LINE_NOT_FOUND = "ANNUAL_REPORT.LINE_NOT_FOUND"
    ANNUAL_REPORT_NOT_FOUND = "ANNUAL_REPORT.NOT_FOUND"
    ANNUAL_REPORT_SIGNER_NAME_MISSING = "ANNUAL_REPORT.SIGNER_NAME_MISSING"
    ANNUAL_REPORT_TAX_CONFLICT = "ANNUAL_REPORT.TAX_CONFLICT"

    # AUDIT
    AUDIT_ENTITY_NOT_FOUND = "AUDIT.ENTITY_NOT_FOUND"
    AUDIT_INVALID_ENTITY_TYPE = "AUDIT.INVALID_ENTITY_TYPE"
    AUDIT_INVALID_ACTOR = "AUDIT.INVALID_ACTOR"
    AUDIT_FORBIDDEN_FIELD = "AUDIT.FORBIDDEN_FIELD"
    AUDIT_PAYLOAD_TOO_LARGE = "AUDIT.PAYLOAD_TOO_LARGE"

    # AUTH
    AUTH_INVALID_PASSWORD_RESET_TOKEN = "AUTH.INVALID_PASSWORD_RESET_TOKEN"
    AUTH_INVALID_REFRESH_TOKEN = "AUTH.INVALID_REFRESH_TOKEN"

    # AUTHORITY_CONTACT
    AUTHORITY_CONTACT_NOT_FOUND = "AUTHORITY_CONTACT.NOT_FOUND"

    # BINDER
    BINDER_ALREADY_FULL = "BINDER.ALREADY_FULL"
    BINDER_ALREADY_HANDED_OVER = "BINDER.ALREADY_HANDED_OVER"
    BINDER_CAPACITY_CHANGE_NOT_ALLOWED = "BINDER.CAPACITY_CHANGE_NOT_ALLOWED"
    BINDER_CLIENT_LOCKED = "BINDER.CLIENT_LOCKED"
    BINDER_CROSS_CLIENT = "BINDER.CROSS_CLIENT"
    BINDER_HANDOVER_INVALID = "BINDER.HANDOVER_INVALID"
    BINDER_INVALID_LOCATION_TRANSITION = "BINDER.INVALID_LOCATION_TRANSITION"
    BINDER_NOT_FOUND = "BINDER.NOT_FOUND"
    BINDER_NOT_FULL = "BINDER.NOT_FULL"
    BINDER_NOT_INTAKE_ELIGIBLE = "BINDER.NOT_INTAKE_ELIGIBLE"
    BINDER_NOT_READY_FOR_HANDOVER = "BINDER.NOT_READY_FOR_HANDOVER"
    BINDER_OFFICE_NUMBER_MISSING = "BINDER.OFFICE_NUMBER_MISSING"
    BINDER_OLD_PERIOD_NOTE_REQUIRED = "BINDER.OLD_PERIOD_NOTE_REQUIRED"

    # BINDER_INTAKE
    BINDER_INTAKE_NOT_FOUND = "BINDER_INTAKE.NOT_FOUND"

    # BUSINESS
    BUSINESS_CLIENT_ALL_CLOSED = "BUSINESS.CLIENT_ALL_CLOSED"
    BUSINESS_CLOSED = "BUSINESS.CLOSED"
    BUSINESS_CONFLICT = "BUSINESS.CONFLICT"
    BUSINESS_FORBIDDEN = "BUSINESS.FORBIDDEN"
    BUSINESS_FROZEN = "BUSINESS.FROZEN"
    BUSINESS_INVALID_STATUS = "BUSINESS.INVALID_STATUS"
    BUSINESS_NAME_CONFLICT = "BUSINESS.NAME_CONFLICT"
    BUSINESS_NOT_DELETED = "BUSINESS.NOT_DELETED"
    BUSINESS_NOT_FOUND = "BUSINESS.NOT_FOUND"

    # BUSINESS_ACTIVITY
    BUSINESS_ACTIVITY_NOT_FOUND = "BUSINESS_ACTIVITY.NOT_FOUND"
    BUSINESS_ACTIVITY_WRONG_CLIENT = "BUSINESS_ACTIVITY.WRONG_CLIENT"

    # CHARGE
    CHARGE_AMOUNT_INVALID = "CHARGE.AMOUNT_INVALID"
    CHARGE_CONFLICT = "CHARGE.CONFLICT"
    CHARGE_INVALID_STATUS = "CHARGE.INVALID_STATUS"
    CHARGE_NOT_FOUND = "CHARGE.NOT_FOUND"

    # CLIENT
    CLIENT_CLOSED = "CLIENT.CLOSED"
    CLIENT_CONFLICT = "CLIENT.CONFLICT"
    CLIENT_DELETED_EXISTS = "CLIENT.DELETED_EXISTS"
    CLIENT_ENTITY_TYPE_CHANGE_FORBIDDEN = "CLIENT.ENTITY_TYPE_CHANGE_FORBIDDEN"
    CLIENT_FROZEN = "CLIENT.FROZEN"
    CLIENT_NOT_DELETED = "CLIENT.NOT_DELETED"

    # CLIENT_RECORD
    CLIENT_RECORD_CLOSED = "CLIENT_RECORD.CLOSED"
    CLIENT_RECORD_NOT_FOUND = "CLIENT_RECORD.NOT_FOUND"

    # CORRESPONDENCE
    CORRESPONDENCE_FORBIDDEN_CONTACT = "CORRESPONDENCE.FORBIDDEN_CONTACT"
    CORRESPONDENCE_NOT_FOUND = "CORRESPONDENCE.NOT_FOUND"

    # DOCUMENT
    DOCUMENT_FILE_TOO_LARGE = "DOCUMENT.FILE_TOO_LARGE"
    DOCUMENT_INVALID_FILE_TYPE = "DOCUMENT.INVALID_FILE_TYPE"
    DOCUMENT_UPLOAD_FAILED = "DOCUMENT.UPLOAD_FAILED"
    DOCUMENT_VERSION_CONFLICT = "DOCUMENT.VERSION_CONFLICT"

    # DOMAIN
    DOMAIN_NOT_FOUND = "DOMAIN.NOT_FOUND"

    # INVOICE
    INVOICE_CONFLICT = "INVOICE.CONFLICT"
    INVOICE_INVALID_STATUS = "INVOICE.INVALID_STATUS"
    INVOICE_NOT_FOUND = "INVOICE.NOT_FOUND"

    # NOTE
    NOTE_FORBIDDEN = "NOTE.FORBIDDEN"
    NOTE_NOT_FOUND = "NOTE.NOT_FOUND"

    # NOTIFICATION
    NOTIFICATION_AUTO_ONLY_TRIGGER = "NOTIFICATION.AUTO_ONLY_TRIGGER"
    NOTIFICATION_AUTO_SEND_TRIGGER_NOT_ALLOWED = "NOTIFICATION.AUTO_SEND_TRIGGER_NOT_ALLOWED"
    NOTIFICATION_BODY_TOO_LONG = "NOTIFICATION.BODY_TOO_LONG"
    NOTIFICATION_EMPTY_BODY = "NOTIFICATION.EMPTY_BODY"
    NOTIFICATION_EMPTY_SUBJECT = "NOTIFICATION.EMPTY_SUBJECT"
    NOTIFICATION_INVALID_IDEMPOTENCY_KEY = "NOTIFICATION.INVALID_IDEMPOTENCY_KEY"
    NOTIFICATION_MISSING_ENTITY_ID = "NOTIFICATION.MISSING_ENTITY_ID"
    NOTIFICATION_MISSING_IDEMPOTENCY_KEY = "NOTIFICATION.MISSING_IDEMPOTENCY_KEY"
    NOTIFICATION_NOT_FOUND = "NOTIFICATION.NOT_FOUND"
    NOTIFICATION_SUBJECT_TOO_LONG = "NOTIFICATION.SUBJECT_TOO_LONG"
    NOTIFICATION_TEMPLATE_ERROR = "NOTIFICATION.TEMPLATE_ERROR"
    NOTIFICATION_VISIBLE_PLACEHOLDER = "NOTIFICATION.VISIBLE_PLACEHOLDER"

    # PERMANENT_DOCUMENTS
    PERMANENT_DOCUMENTS_BUSINESS_NOT_FOUND = "PERMANENT_DOCUMENTS.BUSINESS_NOT_FOUND"
    PERMANENT_DOCUMENTS_CLIENT_RECORD_NOT_FOUND = "PERMANENT_DOCUMENTS.CLIENT_RECORD_NOT_FOUND"
    PERMANENT_DOCUMENTS_CLIENT_SCOPE_VIOLATION = "PERMANENT_DOCUMENTS.CLIENT_SCOPE_VIOLATION"
    PERMANENT_DOCUMENTS_NOT_FOUND = "PERMANENT_DOCUMENTS.NOT_FOUND"

    # REMINDER
    REMINDER_INVALID_STATUS = "REMINDER.INVALID_STATUS"
    REMINDER_NOT_FOUND = "REMINDER.NOT_FOUND"

    # SIGNATURE_REQUEST
    SIGNATURE_REQUEST_EXPIRED = "SIGNATURE_REQUEST.EXPIRED"
    SIGNATURE_REQUEST_INVALID_STATUS = "SIGNATURE_REQUEST.INVALID_STATUS"
    SIGNATURE_REQUEST_INVALID_TYPE = "SIGNATURE_REQUEST.INVALID_TYPE"
    SIGNATURE_REQUEST_NOT_FOUND = "SIGNATURE_REQUEST.NOT_FOUND"
    SIGNATURE_REQUEST_TOKEN_INVALID = "SIGNATURE_REQUEST.TOKEN_INVALID"

    # TASK
    TASK_CLIENT_SOURCE_MISMATCH = "TASK.CLIENT_SOURCE_MISMATCH"
    TASK_CONFLICT = "TASK.CONFLICT"
    TASK_INVALID_ASSIGNEE = "TASK.INVALID_ASSIGNEE"
    TASK_INVALID_SOURCE = "TASK.INVALID_SOURCE"
    TASK_NOT_FOUND = "TASK.NOT_FOUND"

    # TAX_CALENDAR
    TAX_CALENDAR_DEADLINE_RULE_MISSING = "TAX_CALENDAR.DEADLINE_RULE_MISSING"
    TAX_CALENDAR_INVALID_OBLIGATION_TYPE = "TAX_CALENDAR.INVALID_OBLIGATION_TYPE"
    TAX_CALENDAR_INVALID_PERIOD = "TAX_CALENDAR.INVALID_PERIOD"
    TAX_CALENDAR_INVALID_PERIOD_ALIGNMENT = "TAX_CALENDAR.INVALID_PERIOD_ALIGNMENT"
    TAX_CALENDAR_INVALID_PERIOD_FREQUENCY = "TAX_CALENDAR.INVALID_PERIOD_FREQUENCY"
    TAX_CALENDAR_INVALID_TAX_YEAR = "TAX_CALENDAR.INVALID_TAX_YEAR"
    TAX_CALENDAR_LINK_CONFLICT = "TAX_CALENDAR.LINK_CONFLICT"
    TAX_CALENDAR_NOT_FOUND = "TAX_CALENDAR.NOT_FOUND"

    # TAX_ENGINE
    TAX_ENGINE_INVALID_INPUT = "TAX_ENGINE.INVALID_INPUT"

    # TIMELINE
    TIMELINE_CLIENT_NOT_FOUND = "TIMELINE.CLIENT_NOT_FOUND"

    # USER
    USER_CONFLICT = "USER.CONFLICT"
    USER_FORBIDDEN = "USER.FORBIDDEN"
    USER_INVALID_DATE_RANGE = "USER.INVALID_DATE_RANGE"
    USER_INVALID_PASSWORD = "USER.INVALID_PASSWORD"
    USER_INVALID_UPDATE = "USER.INVALID_UPDATE"
    USER_NOT_FOUND = "USER.NOT_FOUND"
    USER_NO_FIELDS_PROVIDED = "USER.NO_FIELDS_PROVIDED"

    # VAT
    VAT_AMENDED_ITEM_NOT_FILED = "VAT.AMENDED_ITEM_NOT_FILED"
    VAT_AMENDED_ITEM_NOT_FOUND = "VAT.AMENDED_ITEM_NOT_FOUND"
    VAT_AMENDED_ITEM_WRONG_CLIENT = "VAT.AMENDED_ITEM_WRONG_CLIENT"
    VAT_AMENDMENT_CYCLE = "VAT.AMENDMENT_CYCLE"
    VAT_AMENDMENT_ID_REQUIRED = "VAT.AMENDMENT_ID_REQUIRED"
    VAT_ASSIGNEE_REQUIRED = "VAT.ASSIGNEE_REQUIRED"
    VAT_CLIENT_CLOSED = "VAT.CLIENT_CLOSED"
    VAT_CLIENT_EXEMPT = "VAT.CLIENT_EXEMPT"
    VAT_CLIENT_RECORD_NOT_FOUND = "VAT.CLIENT_RECORD_NOT_FOUND"
    VAT_CONFLICT = "VAT.CONFLICT"
    VAT_COUNTERPARTY_ID_REQUIRED = "VAT.COUNTERPARTY_ID_REQUIRED"
    VAT_EXPENSE_CATEGORY_REQUIRED = "VAT.EXPENSE_CATEGORY_REQUIRED"
    VAT_FILED_IMMUTABLE = "VAT.FILED_IMMUTABLE"
    VAT_INVALID_STATUS = "VAT.INVALID_STATUS"
    VAT_INVALID_TRANSITION = "VAT.INVALID_TRANSITION"
    VAT_JUSTIFICATION_REQUIRED = "VAT.JUSTIFICATION_REQUIRED"
    VAT_MISSING_FINAL_AMOUNT = "VAT.MISSING_FINAL_AMOUNT"
    VAT_NEGATIVE_VAT = "VAT.NEGATIVE_VAT"
    VAT_NET_NOT_POSITIVE = "VAT.NET_NOT_POSITIVE"
    VAT_NOT_FOUND = "VAT.NOT_FOUND"
    VAT_OSEK_PATUR_CEILING_EXCEEDED = "VAT.OSEK_PATUR_CEILING_EXCEEDED"
    VAT_PENDING_NOTE_REQUIRED = "VAT.PENDING_NOTE_REQUIRED"
